### ISSUE TITLE
How to resolve 'The maximum number of statements allowed has been exceeded'

### ISSUE THREAD

**Issue by sunkararp** [shyboylpf/nebula-net#10]
I am getting below error; when tried to bulk ingest data.

System.Exception: SemanticError: The maximum number of statements allowed has been exceeded

**Comment by wey-gu** [comment]
That's the error from the nebula server-side your query string exceeded the allowed length.
What is your bulk ingest query like?

Plz note, we should use:
```
INSERT VERTEX  t3 (p1), t4(p2) VALUES "1": (111, "hello"), "2": (222, "world"), "3":(333, "foo"), "4":(333, "bar");
```
Rather than:
```
INSERT VERTEX  t3 (p1), t4(p2) VALUES "1": (111, "hello");
INSERT VERTEX  t3 (p1), t4(p2) VALUES "2": (222, "world");
INSERT VERTEX  t3 (p1), t4(p2) VALUES "3":(333, "foo");
INSERT VERTEX  t3 (p1), t4(p2) VALUES  "4":(333, "bar");
```

**Comment by sunkararp** [comment]
@wey-gu thanks for the reply.

We did not see this error with Python library!!!

In any case use UPSERT; how does the above syntax change?

**Comment by shyboylpf** [comment]
@sunkararp thanks for your question, there is a limit from nebula-server side, not from our client.
Please ref nebula document.
